#** Security settings for all Content-Security-Policy (CSP) middleware
#* CSP_DEFAULT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "*")
#* CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "stackpath.bootstrapcdn.com", "*")
#* CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "ajax.cloudflare.com", "static.cloudflareinsights.com", "www.google-analytics.com", "ssl.google-analytics.com", "cdn.ampproject.org", "www.googletagservices.com", "pagead2.googlesyndication.com", "stackpath.bootstrapcdn.com", "*")
#* CSP_IMG_SRC = ("'self'", "www.google-analytics.com", "raw.githubusercontent.com", "googleads.g.doubleclick.net", "*")
#* CSP_FONT_SRC = ("'self'", "*")
#* CSP_CONNECT_SRC = ("'self'", "www.google-analytics.com", "*")
#* CSP_OBJECT_SRC = ("'self'", "*")
#* CSP_BASE_URI = ("'self'", "*")
#* CSP_FRAME_ANCESTORS = ("'self'", "*")
#* CSP_FORM_ACTION = ("'self'", "*")
#* CSP_INCLUDE_NONCE_IN = ('script-src', )
#* CSP_MANIFEST_SRC = ("'self'", "*")
#* CSP_WORKER_SRC = ("'self'", "*")
#* CSP_MEDIA_SRC = ("'self'", "*")

#** Private key for the CSP middleware
#* Security settings
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "ajax.cloudflare.com", "static.cloudflareinsights.com", "www.google-analytics.com", "ssl.google-analytics.com", "cdn.ampproject.org", "www.googletagservices.com", "pagead2.googlesyndication.com", "stackpath.bootstrapcdn.com", )
CSP_IMG_SRC = ("'self'",)
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'self'",)
CSP_BASE_URI = ("'self'",)
CSP_FRAME_ANCESTORS = ("'self'",)
CSP_FORM_ACTION = ("'self'",)
CSP_INCLUDE_NONCE_IN = ('script-src', )
CSP_MANIFEST_SRC = ("'self'",)
CSP_WORKER_SRC = ("'self'",)
CSP_MEDIA_SRC = ("'self'",)